#pragma once
#include "vk_types.h"

#define VULKAN_MAX_UI_COUNT 1024

/** @brief The maximum number of stages (such as vertex, fragment, compute, etc.) allowed. */
#define VULKAN_SHADER_MAX_STAGES 8
/** @brief The maximum number of textures allowed at the global level. */
#define VULKAN_SHADER_MAX_GLOBAL_TEXTURES 31
/** @brief The maximum number of textures allowed at the instance level. */
#define VULKAN_SHADER_MAX_INSTANCE_TEXTURES 31
/** @brief The maximum number of vertex input attributes allowed. */
#define VULKAN_SHADER_MAX_ATTRIBUTES 16
/**
 * @brief The maximum number of uniforms and samplers allowed at the
 * global, instance and local levels combined. It's probably more than
 * will ever be needed.
 */
#define VULKAN_SHADER_MAX_UNIFORMS 128

/** @brief The maximum number of bindings per descriptor set. */
#define VULKAN_SHADER_MAX_BINDINGS 32
/** @brief The maximum number of push constant ranges for a shader. */
#define VULKAN_SHADER_MAX_PUSH_CONST_RANGES 32

/**
 * @brief Configuration for a shader stage, such as vertex or fragment.
 */
typedef struct vulkan_shader_stage_config {
    /** @brief The shader stage bit flag. */
    VkShaderStageFlagBits stage;
    /** @brief The shader file name. */
    char file_name[255];

} vulkan_shader_stage_config;

/**
 * @brief The configuration for a descriptor set.
 */
typedef struct vulkan_descriptor_set_config {
    /** @brief The number of bindings in this set. */
    u8 binding_count;
    /** @brief An array of binding layouts for this set. */
    VkDescriptorSetLayoutBinding bindings[VULKAN_SHADER_MAX_BINDINGS];
} vulkan_descriptor_set_config;


struct vulkan_shader_config {
    /** @brief The number of shader stages in this shader. */
    u8 stage_count;
    /** @brief  The configuration for every stage of this shader. */
    vulkan_shader_stage_config stages[VULKAN_SHADER_MAX_STAGES];
    /** @brief An array of descriptor pool sizes. */
    VkDescriptorPoolSize pool_sizes[2];
    /**
     * @brief The max number of descriptor sets that can be allocated from this shader.
     * Should typically be a decently high number.
     */
    u16 max_descriptor_set_count;

    /**
     * @brief The total number of descriptor sets configured for this shader.
     * Is 1 if only using global uniforms/samplers; otherwise 2.
     */
    u8 descriptor_set_count;
    /** @brief Descriptor sets, max of 2. Index 0=global, 1=instance */
    vulkan_descriptor_set_config descriptor_sets[2];

    /** @brief An array of attribute descriptions for this shader. */
    VkVertexInputAttributeDescription attributes[VULKAN_SHADER_MAX_ATTRIBUTES];

} vulkan_shader_config;

typedef struct vulkan_descriptor_state {
    /** @brief The descriptor generation, per frame. */
    u8 generations[3];
    /** @brief The identifier, per frame. Typically used for texture ids. */
    u32 ids[3];
} vulkan_descriptor_state;

typedef struct vulkan_shader_descriptor_set_state {
    /** @brief The descriptor sets for this instance, one per frame. */
    VkDescriptorSet descriptor_sets[3];

    /** @brief A descriptor state per descriptor, which in turn handles frames. Count is managed in shader config. */
    vulkan_descriptor_state descriptor_states[VULKAN_SHADER_MAX_BINDINGS];
} vulkan_shader_descriptor_set_state;

typedef struct vulkan_shader_instance_state {
    /** @brief The instance id. INVALID_ID if not used. */
    u32 id;
    /** @brief The offset in bytes in the instance uniform buffer. */
    u64 offset;

    /** @brief  A state for the descriptor set. */
    vulkan_shader_descriptor_set_state descriptor_set_state;

    /**
     * @brief Instance texture pointers, which are used during rendering. These
     * are set by calls to set_sampler.
     */
    struct texture** instance_textures;
} vulkan_shader_instance_state;

// typedef struct vulkan_shader {
//     /** @brief The block of memory mapped to the uniform buffer. */
//     void* mapped_uniform_buffer_block;

//     /** @brief The shader identifier. */
//     u32 id;

//     /** @brief The configuration of the shader generated by vulkan_create_shader(). */
//     vulkan_shader_config config;

//     /** @brief A pointer to the renderpass to be used with this shader. */
//     vulkan_renderpass* renderpass;

//     /** @brief An array of stages (such as vertex and fragment) for this shader. Count is located in config.*/
//     vulkan_shader_stage stages[VULKAN_SHADER_MAX_STAGES];

//     /** @brief The descriptor pool used for this shader. */
//     VkDescriptorPool descriptor_pool;

//     /** @brief Descriptor set layouts, max of 2. Index 0=global, 1=instance. */
//     VkDescriptorSetLayout descriptor_set_layouts[2];
//     /** @brief Global descriptor sets, one per frame. */
//     VkDescriptorSet global_descriptor_sets[3];
//     /** @brief The uniform buffer used by this shader. */
//     vulkan_buffer uniform_buffer;

//     /** @brief The pipeline associated with this shader. */
//     vulkan_pipeline pipeline;

//     /** @brief The instance states for all instances. @todo TODO: make dynamic */
//     u32 instance_count;
//     vulkan_shader_instance_state instance_states[VULKAN_MAX_MATERIAL_COUNT];

// } vulkan_shader;
