enum {
	MetaType_ThingId = 12,
	MetaType_EntityFlags,
	MetaType_ThingFlags,
	MetaType_R_MeshId,
	MetaType_R_MaterialId,
};
MemberDefinition members_of_Camera[] = {
	{MetaType_v3, "pos", OffsetOf(Camera,pos)},
	{MetaType_v3, "dir", OffsetOf(Camera,dir)},
	{MetaType_f32, "yaw", OffsetOf(Camera,yaw)},
	{MetaType_f32, "pitch", OffsetOf(Camera,pitch)},
	{MetaType_f32, "fov", OffsetOf(Camera,fov)},
	{MetaType_f32, "accel", OffsetOf(Camera,accel)},
	{MetaType_v3, "vel", OffsetOf(Camera,vel)},
	{MetaType_f32, "vel_friction", OffsetOf(Camera,vel_friction)},
};
MemberDefinition members_of_Thing[] = {
	{MetaType_ThingId, "parent", OffsetOf(Thing,parent)},
	{MetaType_ThingId, "next", OffsetOf(Thing,next)},
	{MetaType_ThingId, "prev", OffsetOf(Thing,prev)},
	{MetaType_ThingId, "first", OffsetOf(Thing,first)},
	{MetaType_ThingId, "last", OffsetOf(Thing,last)},
	{MetaType_String, "name", OffsetOf(Thing,name)},
	{MetaType_EntityFlags, "flags", OffsetOf(Thing,flags)},
	{MetaType_ThingFlags, "tflags", OffsetOf(Thing,tflags)},
	{MetaType_v3, "pos", OffsetOf(Thing,pos)},
	{MetaType_v4, "rot", OffsetOf(Thing,rot)},
	{MetaType_v3, "scale", OffsetOf(Thing,scale)},
	{MetaType_Rng3, "aabb", OffsetOf(Thing,aabb)},
	{MetaType_v3, "vel", OffsetOf(Thing,vel)},
	{MetaType_R_MeshId, "mesh", OffsetOf(Thing,mesh)},
	{MetaType_R_MaterialId, "mat", OffsetOf(Thing,mat)},
	{MetaType_u32, "color", OffsetOf(Thing,color)},
	{MetaType_f32, "elapsed", OffsetOf(Thing,elapsed)},
	{MetaType_u8, "buf0", OffsetOf(Thing,buf0)},
	{MetaType_f32, "modify0", OffsetOf(Thing,modify0)},
	{MetaType_u8, "buf1", OffsetOf(Thing,buf1)},
	{MetaType_f32, "modify1", OffsetOf(Thing,modify1)},
	{MetaType_u8, "buf2", OffsetOf(Thing,buf2)},
	{MetaType_f32, "modify2", OffsetOf(Thing,modify2)},
	{MetaType_u8, "buf3", OffsetOf(Thing,buf3)},
	{MetaType_f32, "modify3", OffsetOf(Thing,modify3)},
	{MetaType_f32, "angle", OffsetOf(Thing,angle)},
};
